### ISSUE TITLE
Storing Passwords in Plain Text

### ISSUE THREAD

**Issue by dfanara** [TheBrainOfThePanda/authme.sk#2]
authme.sk stores player passwords in plain text. This is terrible practice and a huge security flaw. This [Stackoverflow answer](https://stackoverflow.com/a/1197512) explains why storing passwords in plain text is bad. If you are going to continue distributing this skript to players on Spigot forums, then passwords should be hashed and salted before they are stored.

**Comment by rentedpandas** [comment]
Thank you for your comment. This issue has been resolved in version 2.0 of the script.
